updated add and subtract to newer function template

diff --git a/math_operations/operators/add b/math_operations/operators/add
--- a/math_operations/operators/add
+++ b/math_operations/operators/add
@@ -1,16 +1,37 @@
 #! /bin/bash
 
+
 function add()
 {
 	local a="$1"
 	local b="$2"
 	local answer=$(( a+b ))
+	local ret_status=0
+	
 	echo "$answer"
-}
-function main()
-{
-	echo "$(add $1 $2)"
-	return "$?"
+	
+	return $ret_status
 }
 
-main "$1" "$2"
+
+function main()
+{
+	### workaround to handle the pitfall of local declaration changing the return status (#?) - 'add_func_result' must be globaly unique
+	add_func_result=$(add "$1" "$2")
+	local ret_status="$?"
+	###
+	local result="$add_func_result"
+	
+	if [[ "$ret_status" -eq 0 ]]; then
+		echo "$result"
+	fi
+	
+	exit "$ret_status"
+}
+
+
+# in case of running as a script
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+    main "${@}"
+fi
+
diff --git a/math_operations/operators/subtract b/math_operations/operators/subtract
--- a/math_operations/operators/subtract
+++ b/math_operations/operators/subtract
@@ -1,16 +1,36 @@
 #! /bin/bash
 
+
 function substract()
 {
 	local a="$1"
 	local b="$2"
 	local answer=$(( a-b ))
+	local ret_status=0
+	
 	echo "$answer"
-}
-function main()
-{
-	echo "$(substract $1 $2)"
-	return "$?"
+	
+	return $ret_status
 }
 
-main "$1" "$2"
+function main()
+{
+	### workaround to handle the pitfall of local declaration changing the return status (#?) - 'substract_func_result' must be globaly unique
+	substract_func_result=$(substract "$1" "$2")
+	local ret_status="$?"
+	###
+	local result="$substract_func_result"
+	
+	if [[ "$ret_status" -eq 0 ]]; then
+		echo "$result"
+	fi
+	
+	exit "$ret_status"
+}
+
+
+# in case of running as a script
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+    main "${@}"
+fi
+
